Updates to examples - no schema change
NeTEx-CEN/NeTEx pull request #103
Opened 2020-07-28 22:44 UTC by nick-knowles

2022-04-13 20:51 UTC, skinkie commented
I guess this one is outdated, if the examples are not in master yet. Feel free to take the examples but absolutely not the rest.

2022-04-14 12:57 UTC, ue71603 requested changes
The XSD parts can be omitted. When then NeTEx.spp and REadme.md are removed from the PR, then I think we can try to merge it.

2022-04-14 12:57 UTC, ue71603 commented on NeTEx.spp
>  				<Folder FolderName="epip">
Remove NeTEx.spp from PR.

2022-04-14 12:57 UTC, ue71603 commented on README.md
> +Version 1.20 - Base version plus  further minor fixes comprising##
Remove README.md from PR

2022-04-14 12:57 UTC, ue71603 commented on xsd/NeTEx_publication.xsd
>  				<Contributor>CEN TC278 WG3 SG9 Team.</Contributor>
These changes are in my view already in one of the other PR. Here I think we can omit them. @nick-knowles or don't you agree?

2022-04-14 12:57 UTC, ue71603 commented on xsd/netex_framework/netex_genericFramework/netex_organisation_version.xsd
>  <?xml version="1.0" encoding="iso-8859-1"?>
Also done in other PR. Can be removed here.

2022-04-14 12:57 UTC, ue71603 commented on xsd/netex_part_2/part2_journeyTimes/netex_coupledJourney_version.xsd
>  				<Date>
In different PR, can be removed here.

2022-04-14 12:57 UTC, ue71603 commented on xsd/netex_part_2/part2_journeyTimes/netex_flexibleService_version.xsd
>  	<xsd:include schemaLocation="netex_flexibleService_support.xsd"/>
In different PR. Can be removed here.

2022-04-14 23:14 UTC, skinkie commented on xsd/NeTEx_publication.xsd
> +<!-- =====TypeOfLine unique========================== -->
@ue71603 This looks that this is new, but is actually already in.

2022-04-14 23:15 UTC, skinkie commented
Changes are already in current master.

2022-04-14 23:15 UTC, closed without merging