Fix typo on UicFacility  enumeration value allinclusivePrice
NeTEx-CEN/NeTEx pull request #115
Opened 2020-08-12 09:16 UTC by nick-knowles

corerctfrom AllIInclusivePrice AllInclusivePrice

UicServiceFacility value -

 \netex_facilityUic_support.xsd

2020-08-12 09:19 UTC, skinkie commented on README.md
> +### 2020.08.12   FIX  Typo on _AllInclusivePrice_	to  __UicProductCharacteristics__  /  ___
I doubt this all is in the change request.

2022-04-14 12:35 UTC, ue71603 requested changes
I suggest to omit the README.md and just to the PR for the other file. Otherwise we merge an old README.md into the new one.

2022-04-15 08:27 UTC, Aurige approved these changes

2022-04-15 08:31 UTC, skinkie commented
@Aurige the other pull request... #320

2022-04-15 08:35 UTC, Aurige commented
I only see the README.md in 320 not the typo correction itself

2022-04-15 08:46 UTC, skinkie commented
> I only see the README.md in 320 not the typo correction itself

https://github.com/NeTEx-CEN/NeTEx/pull/320/files

2022-04-15 10:12 UTC, closed without merging