Fix documentation of ScopeOfTicketsAvailable
NeTEx-CEN/NeTEx pull request #232
Opened 2021-09-08 15:16 UTC by frodrigo

2021-09-08 15:56 UTC, Aurige approved these changes

2021-09-23 13:26 UTC, skinkie requested changes

2021-09-23 13:27 UTC, skinkie approved these changes

2021-09-23 13:29 UTC, Aurige approved these changes
Ok here, but we allso need to correct the scope enum itself !

2021-09-23 13:32 UTC, skinkie commented
> Ok here, but we allso need to correct the scope enum itself !

Which enum? Any line?

2021-09-23 13:37 UTC, Aurige commented
https://github.com/NeTEx-CEN/NeTEx/issues/235

2021-09-27 15:13 UTC, merged