TicketingFacilityEnumeration to ScopeOfTicketEnumeration
NeTEx-CEN/NeTEx pull request #243
Opened 2021-09-23 23:07 UTC by skinkie

Fix #235

2021-09-24 07:41 UTC, Aurige approved these changes

2021-09-24 09:46 UTC, syversenkr requested changes
1) Not backwards compatible, obviously, but being a bug this fix is necessary. Do we need a deprecation/grace period?

2) I believe the fix on line 1289 should be reverted, because
	<xsd:element name="TicketingFacility" type="TicketingFacilityEnumeration" default="unknown">
should **remain** of TicketingFacilityEnumeration, as this is the "Types of TICKETING available" (i.e. "Allowed values for TicketingFacility")

However, on line line 1277 the ScopeOfTicketList should be of ScopeOfTicketListOfEnumerations type (**not** "TicketingFacilityListOfEnumerations")
I.e. change  to:
	<xsd:element name="ScopeOfTicketList" type="ScopeOfTicketListOfEnumerations">

2022-04-14 12:23 UTC, ue71603 approved these changes

2022-04-14 19:08 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
> +	<xsd:element name="TicketingFacility" type="ScopeOfTicketEnumeration" default="unknown">
```suggestion
	<xsd:element name="TicketingFacility" type="TicketingFacilityEnumeration" default="unknown">
```

2022-04-14 19:11 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
> +		<xsd:list itemType="ScopeOfTicketEnumeration"/>
```suggestion
		<xsd:list itemType="TicketingFacilityListOfEnumerations"/>
```

2022-04-14 19:11 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
> +		<xsd:list itemType="TicketingFacilityListOfEnumerations"/>
```suggestion
		<xsd:list itemType="TicketingFacilityEnumerations"/>
```

2022-04-14 19:12 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_facility_version.xsd
> +		<xsd:list itemType="TicketingFacilityEnumerations"/>
```suggestion
		<xsd:list itemType="TicketingFacilityEnumeration"/>
```

2022-04-14 19:14 UTC, merged