Having multiple BookingNotes
NeTEx-CEN/NeTEx pull request #447
Opened 2023-06-14 08:45 UTC by ue71603

In some cases multiple BookingNotes need to be send (espeicially when one uses text blocks).

2023-06-14 13:47 UTC, skinkie requested changes
Don't like. This does not allow order, and it introduces an ungrouped set of elements. I would say make it BookingNotes (as choice).

2023-06-20 16:08 UTC, Aurige commented
I would also preferably go via a BookingNote**s** to group them ... or add a NoticeAssignment if you want an order (but you can already do it without the need of being explicit)

2023-06-21 12:26 UTC, ue71603 commented
@Aurige @skinkie  We can remove BookingNote and make BookingArrangements a DataManagedobject, then Notice and NoticeAssignment are always available to BookingArrangements. I think this is better as Contact IS a DataManagedObject, but BookingArrangements is not. I redo the PR in this direction.

2023-11-04 00:22 UTC, skinkie commented
@ue71603 do you want to keep this since #525 is in my perspective allowing multiple bookingArrangements, each having a single note. So unless you want to go for _bookingNotes_, for something that is really beyond a multiline note. I don't like that you would have to go in the notice and noticeAssignment direction for simple cases.

2023-11-06 08:49 UTC, ue71603 commented
Ok we close it.

2023-11-06 08:49 UTC, closed without merging