Prefix netex as namespace of DistributionGroupRef
NeTEx-CEN/NeTEx pull request #449
Opened 2023-06-16 12:06 UTC by skinkie

Fix #448

2023-06-16 12:13 UTC, skinkie commented
@ue71603 can you take a peak how to make the examples working?

2023-06-17 18:24 UTC, ue71603 commented
@skinkie  I think the part iabout the DistributionGroupRef is not needed as DistributionGroupRef is a restriction of the GeneralGroupOfEntitiesRefStructure
`				</xsd:element>
				<xsd:element name="DistributionGroupRef" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>Prefined Group of specified points to which  distribution is restricted, if any.</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:restriction base="GeneralGroupOfEntitiesRefStructure">
								<xsd:attribute name="nameOfMemberClass" `

What do you think?
The other occasions with a | are  only related by SubstitutionGroup

2023-06-17 18:59 UTC, skinkie commented
I think we should have at least one example that actually _is_ using a DistributionGroupRef. It is obviously that since we started fixing the constraints these issues popped up.

2023-06-17 20:56 UTC, ue71603 commented
The failed ones used it:

`<GroupOfPlaces version="1.0" id="frst:travel_shops">
`

`<DistributionGroupRef version="1.0" ref="frst:Travel_shops"/>
`

2023-06-17 20:56 UTC, ue71603 commented
what do you think about the latest commit?

2023-06-17 21:09 UTC, ue71603 commented
...at least the DistributionGroupRef is fixed...

2023-06-17 21:24 UTC, skinkie commented on xsd/NeTEx_publication.xsd
> +						SingleJourneyPath, VehicleMeetingPoi
Something fishie happened here.

2023-06-17 21:25 UTC, skinkie commented on xsd/NeTEx_publication.xsd
> +						SingleJourneyPath, VehicleMeetingPoi
```suggestion
						SingleJourneyPath, VehicleMeetingPointInPath, SingleJourney, GroupOfSingleJourneys.
						VehiclePoolerProfile (USerProfile)
```

2023-06-17 21:26 UTC, skinkie commented on xsd/NeTEx_publication.xsd
> +						VehiclePoolerProfile (USerProfile)
```suggestion
						 VehiclePoolerProfile (USerProfile)
```

2023-06-20 09:58 UTC, ue71603 commented on examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
> +							<!-- no version, not validated (and also not in this file) -->
```suggestion
							<DistributionGroupRef ref="nr:OysterTicketShops" version="any"/>
```

2023-06-20 09:59 UTC, ue71603 commented on examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
> +							<!-- no version, not validated (and also not in this file) -->
was already that way.. tried to fix it now.

2023-06-20 10:02 UTC, skinkie commented on examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
> +							<DistributionGroupRef ref="nr:OysterTicketShops" version="any"/>
```suggestion
							<DistributionGroupRef version="any" ref="nr:OysterTicketShops" />
```

2023-06-20 14:52 UTC, Aurige requested changes

2023-06-20 14:57 UTC, ue71603 commented on examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
> +							<DistributionGroupRef version="any" ref="tfl:Visitor_Centres"/>
it worked fined. There is no nr:Visitor_Centers that could be referenced. And the id are per class so it works as well. The id references the GeneralGroupOfEntities (and there is only tfl:Visitor_Centres):
`						<GeneralGroupOfEntities version="any" id="tfl:Visitor_Centres" nameOfMemberClass="AccessSpace">
							<Name>List of visitor centres</Name>
							<members>
								<AccessSpaceRef version="1" ref="tfl:Piccadilly_Circus_Visitor_Centre"/>
								<AccessSpaceRef version="1" ref="tfl:Euston_Station_Visitor_Centre"/>
								<AccessSpaceRef version="1" ref="tfl:Victoria_Station_Visitor_Centre"/>
								<AccessSpaceRef version="1" ref="tfl:Heathrow_Terminal_123_Visitor_Centre"/>
							</members>
						</GeneralGroupOfEntities>`

it does not reference to the DistributionChannel:
`<DistributionChannel version="any" id="tfl:Visitor_Centres">
							<Name>Visitor centres</Name>
							<PaymentMethods>debitCard creditCard companyCheque cash</PaymentMethods>
							<DistributionGroupRef version="any" ref="tfl:Visitor_Centres"/>
						</DistributionChannel>`

2023-06-21 09:04 UTC, Aurige commented on examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
> +							<DistributionGroupRef version="any" ref="tfl:Visitor_Centres"/>
I'm lost here:  in this example _tfl:Visitor_Centres_ is the id of the _DistributionChannel_  `<DistributionChannel version="any" id="tfl:Visitor_Centres">` that has an element refering itself as a _DistributionGroup_ ! I don't get the semantinc, neither the technical side of it !

2023-06-21 09:12 UTC, ue71603 commented on examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
> +							<DistributionGroupRef version="any" ref="tfl:Visitor_Centres"/>
@Aurige  This is no my example. I just made it working. That the DistributionChannel and the Group used the same id text I don't know.  Who knows? @nick-knowles ?

2023-06-21 09:22 UTC, Aurige commented on examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
> +							<DistributionGroupRef version="any" ref="tfl:Visitor_Centres"/>
in fact it was ok with a different namespace, but changing the namespace to "tfl" create an inconsistency !

2023-06-21 09:25 UTC, ue71603 commented
My fault, but: It was only ok, because  no "version" was defined. With a version it no longer validated. And the other GroupofEntities was not in existance. So I used the one that was there.

2023-12-16 16:30 UTC, ue71603 commented on examples/functions/fares/Netex_101.21_TfL_GeographicFares_UnitZone_MultipleProduct.xml
> +							<DistributionGroupRef version="any" ref="tfl:Visitor_Centres"/>
```suggestion
							<DistributionGroupRef version="any" ref="nr:Visitor_Centres"/>
```

2023-12-20 11:48 UTC, Aurige approved these changes

2024-02-16 18:05 UTC, trurlurl approved these changes

2024-02-19 21:39 UTC, merged