Njsk 1.09 rollup;  fix constraints and new examples
NeTEx-CEN/NeTEx pull request #50
Opened 2019-02-25 15:07 UTC by nick-knowles

This is intended to be a corrected baseline before  adding the 1.1 review comment enhancements.
It rolls up 
  (a) Various missing minor fixes from the 1.09  verioin
  (b) Other interim fixes from  no, nl etc. 
  (c) Some new examples
  (d) Some minor documentation corrections

2019-02-26 03:49 UTC, skinkie commented on xsd/netex_part_1/part1_tacticalPlanning/netex_fareZone_version.xsd
> +									<xsd:documentation>Other fare zone that are wholly  included in the  FARE ZONE.</xsd:documentation>
two extra spaces

2019-02-26 03:49 UTC, skinkie commented on xsd/netex_part_1/part1_tacticalPlanning/netex_fareZone_version.xsd
> +					<xsd:documentation>Other fare zone that are wholly  included in the  FARE ZONE.</xsd:documentation>
two extra spaces

2019-02-26 03:50 UTC, skinkie commented on xsd/netex_part_1/part1_tacticalPlanning/netex_fareZone_version.xsd
> +					<Modified>20109-02-25</Modified>UK-05 Fix: Introduce a dummy Tariffzone  so that Fare zone can be a specialisation of TariffZone. Workaround to XMLSPY issue.
extra space

2019-02-26 03:51 UTC, skinkie commented on xsd/netex_part_1/part1_tacticalPlanning/netex_fareZone_support.xsd
> +					<Modified>20109-02-25</Modified>UK-05 Fix: Introduce a dummy TariffZoneRref_ so that FareZone can be a specialisation of TariffZone. Workaround to XMLSPY sg  issue.
what kind of issue? extra space.

2019-02-26 04:09 UTC, skinkie commented on xsd/netex_framework/netex_genericFramework/netex_zone_support.xsd
> +					<Modified>20109-02-25</Modified>UK-05 Fix: Introduce a dummy TariffzoneRef so that Fare zone can be a specialisation of TariffZone. Workaround to XMLSPY issue.
20109

2022-04-14 13:01 UTC, ue71603 approved these changes

2022-04-14 13:03 UTC, ue71603 requested changes
This is a very old PR and also we haddd Nddf

2022-04-14 13:03 UTC, ue71603 commented
I think we should close this PR. I guess most was done in new_modes anyhow. @nick-knowles  @Aurige  @skinkie : What do you think?

2022-04-14 23:04 UTC, skinkie commented
@ue71603 agreed.

2022-04-14 23:04 UTC, closed without merging