Extended dated vehicle journey+replace pr368 and pr411
NeTEx-CEN/NeTEx pull request #518
Opened 2023-10-06 14:57 UTC by Aurige

Update of the [Pr411 ](https://github.com/NeTEx-CEN/NeTEx/pull/411) (that was merged and rolled back due to issues with examples uising UIC periods).
This new version integrates the decisions from the Meeting #13 on October 5th:
- Update of examples to use OperatingDayRef in dated jouneys (keep the old UIC periods commented with an explicit mention of the deprecation).
- UicOperatingPeriod deletion is now replaced by a simple deprecation (clearly stated in comments) for backward compatibility reasons.

2023-10-06 15:25 UTC, skinkie commented
@Aurige you make a reference to an OperatingDay, is this defined in the file?

2023-10-06 15:29 UTC, Aurige commented
> @Aurige you make a reference to an OperatingDay, is this defined in the file?

no, it is most likely that OpertatingDays can be shared across multiple such files and therefore exchanged separately in a calendar frame.

2023-10-06 15:30 UTC, skinkie commented
Lets not go into the direction that we share examples that do not validate on their own.

2023-10-06 15:33 UTC, Aurige commented
> Lets not go into the direction that we share examples that do not validate on their own.

I checked validation with XML Spy (and external Ref are OK ...)

2023-10-06 15:53 UTC, skinkie commented on examples/standards/era_uic/Netex_era_uic_joiningsplitting.xml
> +							<OperatingDayRef ref="tap:OperatingDay:2009-03-21"/>
This is not an external ref, and is missing a version.

2023-10-09 08:16 UTC, skinkie commented on examples/standards/era_uic/Netex_era_uic_joiningsplitting.xml
> +							<OperatingDayRef ref="tap:OperatingDay:2009-03-21" versionRef="1"/> <!-- reference to an  OperationalDay defined in another dataset -->
Just no. There is no reason **not** to include it in this example.

2023-10-12 13:00 UTC, EU-Agency-for-Railways requested changes
I reviewed the changes on the examples and the restriction to one operational day makes them useless for the purpose to explain the usage of NeTEx to replace the existing EDIFACT messages for the timetable data exchange for rail. Rail timetables are usually not planned for a specific operation day. So there is always a validity period plus a bitmask explaining the operating days. I would suggest to redraft the examples with a more suitable element (e.g. ServiceJourney).

2023-10-12 14:02 UTC, Aurige commented
thanks @EU-Agency-for-Railways 
I agreed that the best way to go is to rework these examples and built new cleaner ones using ServiceJourney
This raised a few questions:

- What do we do with the current examples ? do we just temporary drop them or deprecate them, waiting for the new version ?
- Who can contribute to building new examples ? It's quite  lot of examples to update (15 examples, some being quite long)... expect probably a few days to fully redesign and rebuilt them.

Also I would like to separate the XSD from the XML example updates, so it this is Ok for you, I'm going to remove the examples from this PR and create a new separate one for their update.

2023-10-13 09:25 UTC, Aurige commented
@skinkie I reverted all changes to examples but had issues with other commits that were automatically brought back by Github and that were also modifying and breaking this PR... I had to revert it, but now it's a total mess ... I'm not sure what happened, but I'm afraid that I need to recreate this PR once more !!

2023-10-13 09:49 UTC, skinkie commented
@Aurige if you have a lot of free time, I have more interesting things to discuss ;-)

2023-10-13 10:12 UTC, Aurige commented
replaced by https://github.com/NeTEx-CEN/NeTEx/pull/520

2023-10-13 10:12 UTC, closed without merging