Add external ref to StopPlace and Quay (Fix #451)
NeTEx-CEN/NeTEx pull request #552
Opened 2023-11-08 14:53 UTC by duexw

This is the agreed fix for issue #451 .
New Elements ExternalStopPlaceRef and ExternalQuayRef are added to StopPlace and Quay. 
They can be used for storing national stop and quay identifiers in the case where these do not conform to the ID format described in EPIP .

2023-11-08 16:36 UTC, skinkie commented
@duexw you are now targeting master, but this change is actually for the future schema. That having said, why not use our new privateCodes structure, which may include the "AVMS" as a type?

2023-11-09 16:53 UTC, duexw commented
We would rather not like to use private code, because the intended use is by definition not private. We have some global identifiers in the German VDV standards, which are used to identify the objects across system borders.

We would like to express them in NeTEx as follows

- DLID/DTID (VDV 433): global Line ID: -> ExternalLineRef
- DFID (VDV 433): global Journey ID: -> ExternalVehicleJourneyRef
- DHID (VDV 432): global stop point id -> ExternalStopPointRef
- DHID (VDV 432): global quay  -> ExternalQuayRef
- DHID (VDV 432): global stop place ref  -> ExternalStopPlaceRef

2023-11-21 17:22 UTC, Aurige commented
It's Ok for me but I'd rather target it to next

2023-11-21 22:52 UTC, skinkie commented
I would like to have a discussion about this. In my perspective the whole 'external' thing is something that doesn't make sense to me. If it is _external_ it is by definition _private_ otherwise that external system would have used the NeTEx id in the first place.

2023-11-22 08:36 UTC, duexw commented
OK, I changed the branch from master to next. 
@skinkie : I do not remember why we used the prefix "External" for ExternalLineRef and ExternalVehicleJourneyRef back in the day when these elements were created - but I thought it better to stay in line with the two new ones. And I agree that ideally systems should use the id value directly. However, there are cases where this is not possible. For instance, in VDV 433 the DFID = ExternalVehicleJourneyRef needs to be unique only for one operating day, whereas the Journey id would have to be unique across all journeys and operating days.

2023-11-27 13:30 UTC, trurlurl requested changes

2023-11-27 13:30 UTC, trurlurl commented on xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd
> +					<xsd:documentation>Taxi can now be modeled as VEHICLE MODE as well.</xsd:documentation>
```suggestion
					<xsd:documentation>Taxi can now be modelled as VEHICLE MODE as well.</xsd:documentation>
```

2023-11-27 13:30 UTC, trurlurl commented on xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_support.xsd
> +					<xsd:documentation>An alternative code that uniquely identifies the STOP PLACE. Specifically for use in AVMS systems that require an alias, if. For VDV compatibility.</xsd:documentation>
```suggestion
					<xsd:documentation>An alternative code that uniquely identifies the STOP PLACE. Specifically for use in AVMS systems that require an alias. For VDV compatibility.</xsd:documentation>
```

2023-11-27 13:30 UTC, trurlurl commented on xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd
> +					<xsd:documentation>An alternative code that uniquely identifies the QUAY. Specifically for use in AVMS and journey planning systems that require an alias, if. For VDV compatibility.</xsd:documen
```suggestion
					<xsd:documentation>An alternative code that uniquely identifies the QUAY. Specifically for use in AVMS and journey planning systems that require an alias. For VDV compatibility.</xsd:documentation>
```

2023-11-27 16:05 UTC, ue71603 approved these changes

2023-11-27 16:26 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd
> +					<xsd:documentation>cable railway on steep slope, typcially using two counterbalanced carriages.</xsd:documentation>
```suggestion
					<xsd:documentation>cable railway on steep slope, typically using two counterbalanced carriages.</xsd:documentation>
```

2023-11-27 16:27 UTC, skinkie commented on xsd/netex_framework/netex_genericFramework/netex_assignment_version.xsd
> +			<xsd:documentation>Elements for an ASSIGNMENT. An ASSIGNMENT assigns a property to an another element. It has a name and an order.</xsd:documentation>
```suggestion
			<xsd:documentation>Elements for an ASSIGNMENT. An ASSIGNMENT assigns a property to another element. It has a name and an order.</xsd:documentation>
```

2023-11-27 16:27 UTC, skinkie commented on xsd/netex_framework/netex_genericFramework/netex_assignment_version.xsd
> +			<xsd:documentation>Dummy Abstract Assignment. An Assignment assigns a property to an other element. It has a name and an order.</xsd:documentation>
```suggestion
			<xsd:documentation>Dummy Abstract Assignment. An Assignment assigns a property to another element. It has a name and an order.</xsd:documentation>
```

2023-11-30 18:00 UTC, Aurige approved these changes

2023-11-30 19:11 UTC, skinkie commented
I would like to discuss this thing the the merge feast.

2023-12-01 11:38 UTC, skinkie commented
@ue71603 it should still work. Especially for everyone that has upgraded their libxml2 stuff :-)

2023-12-13 13:41 UTC, ue71603 commented
Nick: Must be moved to SiteComponent
Stefan dK: Why having an External anyway. When we have KeyList. Argument understandable. I would like to remove it from the other object.
Stefan J.: Same.
Stefan dK: PrivateCode also extended.
Wilfried: Then we have a double concept already. In den VDV 462 group it was discussed. They wanted it that way. Dedicated element for this. KeyList is too unspecific.  These id are prime citizens. 
Matthias: SNCF does all id in KeyList. Laurent in Switzerland wants to do it this way as well  Key:"SLOID" Value:"ch:1:StopPlace:8507000"
Nick: I would see it.
Stefan dK: But this is the definition of PrivateCode.
Nick: We should clarify the difference.

2023-12-13 13:47 UTC, ue71603 commented
Christophe: IdF has these things.
Wilfried: PrivateCode is very local. The national identifier are nationwide. They are cross-system.
Wilfried: A main problem was the ":"
Wilfried: Stop, Quay etc. it is ok. In VehicleJourney we have the external reference.

Wilfried: We can close it, when the EPIP close.  Removal of the other entries. Stefan creates a PR to remove it. 

=> EPIP will be done by Christophe.
=> PR for removal Stefan

2023-12-13 13:47 UTC, Aurige commented
There is an overlap between External Refs, PrivateCode and Key lists (more generic extension mechanism)  ... 
The EPIP doc needs to be updated accordingly on the Id codification
Group decision: stick on existing and close

2023-12-13 13:48 UTC, ue71603 commented
Wilfried: We have the German national identifier. Is valid on one day.

2023-12-14 09:09 UTC, skinkie commented
This one should be closed.

2023-12-14 09:09 UTC, closed without merging

2024-01-16 22:48 UTC, nick-knowles commented
Note that  tif one uses just  CODESPACEs, then  there  probably isnt a need for a private /external code (unless there is a different legacy code being exchanged)

Thus rather than
    <StopPlace id="ch:1:StopPlace:8507000">
       <PrivateCode>8507000/>
      instead just
    <StopPlace ="sncf:8507000">

where Codespace "sncf"  is understood to mean the lexical scope for sncf stops

2024-01-17 13:32 UTC, ue71603 commented
> Note that tif one uses just CODESPACEs, then there probably isnt a need for a private /external code (unless there is a different legacy code being exchanged)
> 
> Thus rather than 8507000/> instead just <StopPlace ="sncf:8507000">
> 
> where Codespace "sncf" is understood to mean the lexical scope for sncf stops

In theory yes. In practice often the id are generated by an aggregation enitity and sometimes are only stable during an export. so having an additional id is certainly not a bad idea.

2024-06-20 10:10 UTC, trurlurl commented
Removing "documentation needed" label since closed withoud merging.