Comment NL27
NeTEx-CEN/NeTEx pull request #58
Opened 2019-03-01 16:54 UTC by Aurige

Addition of TypeOfProductCategoryRef  and TypeOfServiceRef on a Line (requires to move them from Part 2 to Part 1)

2021-05-05 22:29 UTC, skinkie commented
Lacks documentation only available;
![image](https://user-images.githubusercontent.com/502394/117217672-0ad79400-ae02-11eb-90e5-4de4192b22cd.png)

2021-05-05 22:49 UTC, skinkie commented
Entire XSD update has been added by @nick-knowles, documentation is not available.

2022-04-13 19:07 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_support.xsd
> +	<xsd:simpleType name="TypeOfServiceIdType">
The first 4 elements are all defined in netex_serviceRestrictions_support.xsd => don't do those here.

2022-04-13 19:09 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_support.xsd
> +	<xsd:simpleType name="TypeOfProductCategoryIdType">
Those are also all in netex_serviceRestrictions_support.xsd. First file already integrated in master.

2022-04-13 19:10 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +	<xsd:complexType name="typesOfServiceInFrame_RelStructure">
in netex_serviceRestrictions_version

2022-04-13 19:12 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +			<xsd:element name="typesOfServices" type="typesOfServiceInFrame_RelStructure" minOccurs="0">
This part is not found.... If needed it stands. @Aurige

2022-04-13 19:12 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +			<xsd:element name="typesOfServices" type="typesOfServiceInFrame_RelStructure" minOccurs="0">
This part is not found.... If needed it stands. @Aurige

2022-04-13 19:13 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +			<xsd:element ref="TypeOfProductCategoryRef" minOccurs="0"/>
This part is also not in master currently.

2022-04-13 19:14 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +	<xsd:element name="TypeOfProductCategory" abstract="false" substitutionGroup="TypeOfValue">
TypeOfProductCategory already in master in netex_serviceRestrictions_version.xd

2022-04-13 19:14 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +	<xsd:element name="TypeOfProductCategory" abstract="false" substitutionGroup="TypeOfValue">
TypeOfProductCategory already in master in netex_serviceRestrictions_version.xd

2022-04-13 19:16 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +						<xsd:sequence>
TypeOfService is in master in netex_serviceRestrictions_version and even with more content:
At this place the version here is missing:
						<xsd:sequence>
							<xsd:group ref="EntityInVersionGroup" minOccurs="0"/>
						</xsd:sequence>

2022-04-13 19:16 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +						<xsd:sequence>
TypeOfService is in master in netex_serviceRestrictions_version and even with more content:
At this place the version here is missing:
						<xsd:sequence>
							<xsd:group ref="EntityInVersionGroup" minOccurs="0"/>
						</xsd:sequence>

2022-04-13 19:17 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +	<xsd:complexType name="TypeOfServiceStructure" abstract="false">
exists already in master TypeOfServiceStructure

2022-04-13 19:17 UTC, ue71603 commented on xsd/netex_part_1/part1_networkDescription/netex_line_version.xsd
> +	<xsd:complexType name="TypeOfServiceStructure" abstract="false">
exists already in master TypeOfServiceStructure

2022-04-13 19:19 UTC, ue71603 commented on xsd/netex_part_2/part2_journeyTimes/netex_journey_version.xsd
> +	<xsd:include schemaLocation="../../netex_part_1/part1_networkDescription/netex_line_support.xsd"/>
Didn't find it in master. But it seed to have worked just fine. Even also without netex_serviceRestrictions_support.xsd. At least this needs to be rechecked, if it should stay in the pull request.

2022-04-13 19:19 UTC, ue71603 commented on xsd/netex_part_2/part2_journeyTimes/netex_journey_version.xsd
> +	<xsd:include schemaLocation="../../netex_part_1/part1_networkDescription/netex_line_support.xsd"/>
Didn't find it in master. But it seed to have worked just fine. Even also without netex_serviceRestrictions_support.xsd. At least this needs to be rechecked, if it should stay in the pull request.

2022-04-13 19:20 UTC, ue71603 requested changes
The PR is mostly done already.  The rest needs to be rechecked and resubmitted.

2022-11-21 08:53 UTC, ue71603 commented
This is one of the old CR.
•	I think first Christophe needs to check, which of the things we should still add
•	Then André can check if everything is in the documentation (from the things we don’t want to add, because they should be there)
•	Then we shrink the CR to what still needs to be done
•	Then we merge it
•	Then we update the rest of the documentation.

2023-11-22 17:18 UTC, Aurige commented
It is already in next so we can close it

2023-11-22 17:18 UTC, closed without merging

2024-07-04 12:53 UTC, trurlurl commented
Removing "needs documentation update" label since closed without having been merged.