Comment NL32
NeTEx-CEN/NeTEx pull request #61
Opened 2019-03-05 11:05 UTC by Aurige

Addition of AccessFacilityList to CommonFacilityGroup (so that we can use it in VehicleType and others entities) Addition of “automaticRamp”, “wheelchairLift”, “slidingStep” to the AccessFacilityEnum

2021-05-06 21:21 UTC, skinkie commented
![image](https://user-images.githubusercontent.com/502394/117366582-44bb9f80-aec1-11eb-9cda-2994cdcc66d8.png)

Pull request is already in master.

2021-05-07 08:08 UTC, Aurige commented
OK for doc update

2022-04-13 18:55 UTC, ue71603 commented on xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
> +			<xsd:enumeration value="wheelchairLift"/>
The changes in netex_facility_support were already made. Only netex_facility_version is missing. I think we can drop the changes to netex_facility_support.xsd

2022-04-13 18:55 UTC, ue71603 commented on xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
> +			<xsd:enumeration value="wheelchairLift"/>
The changes in netex_facility_support were already made. Only netex_facility_version is missing. I think we can drop the changes to netex_facility_support.xsd

2022-04-13 18:56 UTC, ue71603 commented on xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
> +			<xsd:enumeration value="wheelchairLift"/>
@skinkie

2022-04-13 18:56 UTC, ue71603 commented on xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
> +			<xsd:enumeration value="wheelchairLift"/>
@skinkie

2022-04-13 18:56 UTC, ue71603 commented on xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
> +			<xsd:enumeration value="wheelchairLift"/>
sorry it was Christophe @Aurige

2022-04-13 18:56 UTC, ue71603 commented on xsd/netex_framework/netex_reusableComponents/netex_facility_support.xsd
> +			<xsd:enumeration value="wheelchairLift"/>
sorry it was Christophe @Aurige

2022-04-13 20:00 UTC, skinkie approved these changes

2022-04-13 20:27 UTC, skinkie requested changes
If you want it in in CommonFacilityGroup it must be removed from SiteFacilityGroup. Please decide!

2022-04-13 20:33 UTC, skinkie commented
@Aurige if you don't want to have it changed, just close the pull request.

2022-04-15 13:25 UTC, skinkie commented
Can be closed, no changes.

2022-04-15 13:25 UTC, closed without merging

2024-07-04 12:54 UTC, trurlurl commented
Removing "needs documentation update" label since closed without having been merged.