Refactor ChargingEquipmentProfile to RechargingEquipmentProfile
NeTEx-CEN/NeTEx pull request #676
Opened 2024-03-13 10:13 UTC by skinkie

@nick-knowles This is the style of pull request I would like to see from you. A **single change** that can be reviewed and evaluated independently.

To other reviewers: I have already made some typo fixes. I would again like to ask you if you can give this one a review, thanks for your precious time.

2024-03-13 10:49 UTC, ue71603 approved these changes

2024-03-13 10:56 UTC, ue71603 commented
VDV452 ist not working out.... trying to fix it.

2024-03-13 10:57 UTC, skinkie commented
> VDV452 ist not working out.... trying to fix it.

Already fixed.

2024-03-13 10:58 UTC, ue71603 approved these changes
ok you did it.

2024-03-13 10:58 UTC, skinkie commented on xsd/NeTEx_publication.xsd
> +				<xsd:documentation>Every [RechargingPointAssignment Id + Versionr] must be unique within document.</xsd:documentation>
```suggestion
				<xsd:documentation>Every [RechargingPointAssignment Id + Version] must be unique within document.</xsd:documentation>
```

2024-03-13 10:59 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_vehicleType_version.xsd
> +					<xsd:documentation>Members of Vehicle Profile.  +v2.0</xsd:documentation>
```suggestion
					<xsd:documentation>Members of Vehicle Profile. +v2.0</xsd:documentation>
```

2024-03-13 10:59 UTC, skinkie commented on xsd/netex_part_1/part1_ifopt/netex_rechargingPointAssignment_support.xsd
> +		<xsd:documentation>NeTEX: RECHARGING POINT ASSIGNMENT  identifier types.</xsd:documentation>
```suggestion
		<xsd:documentation>NeTEX: RECHARGING POINT ASSIGNMENT identifier types.</xsd:documentation>
```

2024-03-13 11:00 UTC, skinkie commented on xsd/netex_part_1/part1_ifopt/netex_rechargingPointAssignment_support.xsd
> +			<xsd:documentation>Reference to a RECHARGING POINT ASSIGNMENT</xsd:documentation>
```suggestion
			<xsd:documentation>Reference to a RECHARGING POINT ASSIGNMENT.</xsd:documentation>
```

2024-03-13 11:00 UTC, skinkie commented on xsd/netex_part_1/part1_ifopt/netex_rechargingPointAssignment_version.xsd
> +					<xsd:documentation>RECHARGING POINTss in frame. +v2.0 </xsd:documentation>
```suggestion
					<xsd:documentation>RECHARGING POINTss in frame. +v2.0</xsd:documentation>
```

2024-03-13 11:00 UTC, skinkie commented on xsd/netex_part_2/part2_journeyTimes/netex_coupledJourney_support.xsd
> +			<xsd:documentation>A collection of one or more references to a Bkick</xsd:documentation>
```suggestion
			<xsd:documentation>A collection of one or more references to a BLOCK.</xsd:documentation>
```

2024-03-13 11:01 UTC, skinkie commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_support.xsd
> +						<xsd:documentation>Identifier of a RechargingPlan.</xsd:documentation>
```suggestion
						<xsd:documentation>Identifier of a RECHARGING PLAN.</xsd:documentation>
```

2024-03-13 11:01 UTC, skinkie commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_version.xsd
> +					<xsd:documentation>List of RECHARGING PLANS in frame.</xsd:documentation>
```suggestion
					<xsd:documentation>List of RECHARGING PLANs in frame.</xsd:documentation>
```

2024-03-13 11:02 UTC, skinkie commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_version.xsd
> +					<xsd:documentation>Quantity of energy for charging in Watt Hours [Wh]</xsd:documentation>
```suggestion
					<xsd:documentation>Quantity of energy for charging in Watt Hours [Wh].</xsd:documentation>
```

2024-03-13 11:02 UTC, skinkie commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_version.xsd
> +					<xsd:documentation>Duration of the unhooking process</xsd:documentation>
```suggestion
					<xsd:documentation>Duration of the unhooking process.</xsd:documentation>
```

2024-03-13 11:02 UTC, skinkie commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_version.xsd
> +					<xsd:documentation>Duration of the setup process</xsd:documentation>
```suggestion
					<xsd:documentation>Duration of the setup process.</xsd:documentation>
```

2024-03-13 11:02 UTC, skinkie commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_version.xsd
> +									<xsd:documentation>Quantity of energy for charging in Watt Hours [Wh]</xsd:documentation>
```suggestion
									<xsd:documentation>Quantity of energy for charging in Watt Hours [Wh].</xsd:documentation>
```

2024-03-13 11:02 UTC, skinkie commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_version.xsd
> +					<xsd:documentation>Overall quantity of energy for charging in Watt Hours [Wh]</xsd:documentation>
```suggestion
					<xsd:documentation>Overall quantity of energy for charging in Watt Hours [Wh].</xsd:documentation>
```

2024-03-13 14:14 UTC, trurlurl requested changes

2024-03-13 14:14 UTC, trurlurl commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_version.xsd
> +			<xsd:documentation>Elements for RECHARGING STEP.</xsd:documentation>
```suggestion
			<xsd:documentation>Durations of RECHARGING STEP phases.</xsd:documentation>
```

2024-03-13 14:14 UTC, trurlurl commented on xsd/netex_framework/netex_reusableComponents/netex_nm_chargingEquipmentProfile_version.xsd
> +					<xsd:documentation>Charging voltage in Volts.</xsd:documentation>
```suggestion
					<xsd:documentation>Charging voltage in volts.</xsd:documentation>
```

2024-03-13 14:14 UTC, trurlurl commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_support.xsd
> +			<xsd:documentation>Allowed value for RECHARGING PROCESS.</xsd:documentation>
```suggestion
			<xsd:documentation>Allowed value for RECHARGING PROCESS. +v2.0</xsd:documentation>
```

2024-03-13 14:14 UTC, trurlurl commented on xsd/netex_part_2/part2_vehicleService/netex_vehicleRechargingPlan_support.xsd
> +			<xsd:documentation>Allowed value for RECHARGING PROCESS.</xsd:documentation>
For me it isn't completely clear where signalling "+2.0" is needed and where not...

2024-03-13 14:30 UTC, trurlurl approved these changes

2024-03-15 11:57 UTC, Aurige approved these changes

2024-03-19 14:14 UTC, merged