Recharging point & plan revisions
NeTEx-CEN/NeTEx pull request #793
Opened 2024-10-28 00:52 UTC by nick-knowles

Revisions to ReCHARGING EQUIPMENT PROFIEL and RECHARGING PLAN to address VVS issues

a) Add RECHARGING STATION and RECHARGING BAY

b) Allow a VETRHICEL JOURNEY to indicate a preferred VEHICEL EQUIPMENT PROFILE / RECHARGING EQUIPMENT PROFILE

c) ALlow  RECHARGING EQUIPMENT PROFILE to state which  VEHICLE RECHARGING EQUIPMENTs it ios compatible to
to state

2024-10-28 19:04 UTC, duexw requested changes
I am generally OK with the new elements RechargingStation and RechargingBay - many thanks. By re-using the ParkingGroup, we inherit many elements and properties which apply to commercial car parking, but not to recharging public buses. That may be confusing to  implementers. they will have to apply some common sense here.

The "VDV" example needs some adjustment
1) In VDV, the charging point would not be part of the ServiceJourneyPattern - otherwise you would need different ServiceJourneyPatterns depending on whether you actually recharge on a journey or not. VDV just needs the assignment from the scheduled stop point to the recharging bays which could be used from there. This is obviously possible:
![image](https://github.com/user-attachments/assets/60c93519-5141-4996-9090-bf50ac53fa9a)
so that's fine in the model, but not in the example. 

2) Minor issue:
In the XML example, the ValueSet/values/TypeOfPlug is a copy of TypeOf Point. But PlugType "Bus Stop" is confusing
I can help with fixing the VDV example if necessary.

2024-10-29 14:24 UTC, Aurige commented
Update of the VDV Example needed (assign recharging point to Scheduled stop point)
@duexw to propose an update example

2024-11-19 15:03 UTC, Aurige commented
@duexw requirement: Link RechargingStep to Blocks ?

2024-11-28 13:01 UTC, Ulf9 commented on examples/standards/vdv452/timetable/NeTEx VDV Example.xml
Nick has added support for charging cars at dedicated recharging bays, but these bays are related to the general parking concept, implying that the public can recharge their Teslas etc. at these recharging bays.  
The added recharging bays and recharging stations seems fine. But for public use...

The actual VDV need is something else. VDV indicates that they need to model support for opportunity-charging during the time a bus in operation is exchanging passengers at a stop.

They wish to indicate that a certain physical bus stop ( that reads Quay in NeTEx) has an overhead pantograph and also to which recharging station the pantograph is linked.

So forget about recharging bay, which is irrelevant in this case. I also suggest linking the physical Vehicle Recharging-Equipment to the Quay it is serving.  

In the example file create a Quay for each relevant physical bus stop. Thus one Quay per VDV - Scheduled Stop Point. Then assign that Quay to the Scheduled Stop Point. This can easliy be automated as nothing hinders using aligned Ids for Quay, Scheduled Stop Point and Passenger Stop Assignment.

Here is the extended StopPlace:
<StopPlace id="SP_351" version="1">
					<Name>Munzinger Straße</Name>
					<ShortName>MUZ</ShortName>
					<PrivateCode>716</PrivateCode>
					<placeTypes>
						<TypeOfPlaceRef version="1" ref="TypeOfPlace_1"/>
					</placeTypes>
					<PublicCode>30716</PublicCode>
					<Quay id="Q_2662" version="1">
						<PrivateCode>6</PrivateCode>
						<Name>Bus Ri OBE/Haid L11/34</Name>
						<Location>
							<Longitude>47.987805277777774</Longitude>
							<Latitude>7.7959475</Latitude>
							<Altitude>0</Altitude>
						</Location>
						<PublicCode>71606</PublicCode>
						<CompassBearing>146.0</CompassBearing>
					</Quay>
</StopPlace>

And the additional stop assignment:

<PassengerStopAssignment order="1" id="PQA_2662" version="1">
					<ScheduledStopPointRef ref="SSP_2662"" version="1"/>
					<QuayRef ref="Q_2662" version="1"/>
</PassengerStopAssignment>

And the adjusted recharging point assignment:

<RechargingPointAssignment version="1" id="de:vagfr:RechargingPointAssignment:MUZ06">
					<Name>Stop Point SSP_2662 can use Bay MUZ06</Name>
					<QuayRef version="1" ref="Q_2662"/>
					<EquipmentPlaceRef version="1" ref="de:vagfr:EquipmentPlace:MUZ06"/>
					<VehicleChargingEquipmentRef version="1" ref="de:vagfr:VehicleChargingEquipment:31"/>
</RechargingPointAssignment>

2025-01-28 14:52 UTC, duexw commented on examples/standards/vdv452/timetable/NeTEx VDV Example.xml
Ulf, I understand your criticism of using the parkingbay element. However, from a VDV452 / VDV462 perspective, we would not like to use the Quay element and we need the RechargingStation element. I agree on the use of VehicleChargingEquipment though. Could we not just have the VehicleChargingEquipments below RechargingStation, like so:
![image](https://github.com/user-attachments/assets/19eeaafb-ef1b-4bad-b0d1-8529f27f9696)

Then we can assign the ScheduledStopPoint elements to the VehicleChargingEquipments without using Quay and without using Parkingbay:
![image](https://github.com/user-attachments/assets/a5965163-7d1f-4918-881d-bf3d30d18041)

The RechargingStation Element does not need to be below "parkings", it could also have an own enclosing element "rechargingStations"

2025-03-18 13:36 UTC, Ulf9 commented on examples/standards/vdv452/timetable/NeTEx VDV Example.xml
![image](https://github.com/user-attachments/assets/214f921c-95d3-4f5c-aaaf-4757f5c212ff)

Maybe allowing a list of served ScheduledStopPoints ?

2025-03-18 14:48 UTC, Aurige commented on examples/standards/vdv452/timetable/NeTEx VDV Example.xml
WD to update the PR accordingly

2025-04-03 14:13 UTC, ue71603 commented
accept situation with ScheduledStopPoints, but doesn't make really sense.

2025-04-17 16:45 UTC, duexw commented
Yet to be discussed:

- Do we need RechargingBay any more
- VehicleChargingEquipment: Does one use it as a type or as an instance (see example)

2025-04-22 13:01 UTC, skinkie commented on xsd/netex_part_1/part1_ifopt/netex_rechargingPointAssignment_version.xsd
> +			<xsd:element name="servedScheduledStopPoints" type="scheduledStopPointRefs_RelStructure" minOccurs="0" maxOccurs="1">
```suggestion
			<xsd:element name="servedScheduledStopPoints" type="scheduledStopPointRefs_RelStructure" minOccurs="0">
```
maxOccurs is default=1

2025-04-22 13:02 UTC, skinkie commented on xsd/netex_part_1/part1_ifopt/netex_rechargingPointAssignment_version.xsd
> +			<xsd:documentation>Type for a liSt of RECHARGING Stations.</xsd:documentation>
```suggestion
			<xsd:documentation>Type for a list of RECHARGING stations.</xsd:documentation>
```

2025-04-22 13:03 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_version.xsd
> +					<xsd:documentation>Type of Plug supported (Fixed choice).</xsd:documentation>
```suggestion
					<xsd:documentation>Type of Plug supported (fixed choice).</xsd:documentation>
```

2025-04-22 13:03 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_version.xsd
> +				<Date><Modified>2024-10-26</Modified>Plug Type and TypeofPlug )open) to Recharging Equipment
```suggestion
				<Date><Modified>2024-10-26</Modified>Plug Type and TypeofPlug (open) to Recharging Equipment
```

2025-04-22 13:05 UTC, skinkie commented on xsd/netex_part_1/part1_ifopt/netex_rechargingPointAssignment_version.xsd
> +					<xsd:documentation>Total poerravailable to all bays in station.</xsd:documentation>
```suggestion
					<xsd:documentation>Total power available to all bays in station.</xsd:documentation>
```

2025-04-22 13:07 UTC, skinkie commented on xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version.xsd
> +				<Date><Modified>2024-06-24</Modified>Move VEHICOE JOURNEY STOP ASSIGNMENT, TRAIN COMPONENT LABEL ASSIGNMENT and  VEHICLE JOURNEY STOP ASSIGNMENT to separate file
```suggestion
				<Date><Modified>2024-06-24</Modified>Move VEHICLE JOURNEY STOP ASSIGNMENT, TRAIN COMPONENT LABEL ASSIGNMENT and  VEHICLE JOURNEY STOP ASSIGNMENT to separate file
```

2025-04-22 13:07 UTC, skinkie commented on xsd/netex_part_2/part2_journeyTimes/netex_vehicleJourney_version.xsd
> +				<Date><Modified>2024-10-24</Modified>VEHICLE JOURNEY needs to be able to ref a  preferred VEHICLE EQUIPMENT PROFILE.
```suggestion
				<Date><Modified>2024-10-24</Modified>VEHICLE JOURNEY needs to be able to ref a preferred VEHICLE EQUIPMENT PROFILE.
```

2025-05-23 10:44 UTC, Aurige commented
merged next again to the branch to get he latest changes

2025-05-23 10:57 UTC, Aurige approved these changes
It looks Ok for me (usable) and  I would be happy to quickly merge it so we have something workable (note that a first version of recharging plan is already in the XSD and in the documentation). Even if this version is not perfect, it was enhanced, improved and this is better than the original first draft.

2025-05-23 11:15 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_support.xsd
> +			<xsd:enumeration value="tpg"/>
What is tpg?

2025-05-23 11:16 UTC, skinkie commented on xsd/netex_part_1/part1_ifopt/netex_ifopt_site_version.xsd
> +				<Date><Modified>2020-10-10</Modified>New Modes : Add PRESENTATION To Site ELement
```suggestion
				<Date><Modified>2020-10-10</Modified>New Modes : Add PRESENTATION To Site Element
```

2025-05-23 14:55 UTC, Aurige commented on xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_support.xsd
> +			<xsd:enumeration value="tpg"/>
No idea (except Transports Publics Genevois  ;-) )

2025-05-23 20:11 UTC, trurlurl commented on xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_support.xsd
> +			<xsd:enumeration value="tpg"/>
Perhaps this was meant to be "lpg" - liquified petrol gas, also called autogas? It would be equivalent to liquidGas. lpg is stored at about 10 bar.
Then there is "cng" - compressed natural gas - stored at much higher pressure. A vehicle accepting cng works with naturalGas, bioGas (not in the list), and methane. Methane is the main ingredient of both naturalGas and bioGas.

There are still more problems, in my view. For a "dieselBatteryHybrid" vehicle, I would put all the following in *FuelType*: dieselBatteryHybrid, diesel, biodiesel, perhaps electricContact, electricity (but not battery, except if there is the possibility to replace an empty battery). 
Doesn't all this require some clarifications, rework, or annotations?

2025-05-23 21:24 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_support.xsd
> +			<xsd:enumeration value="tpg"/>
If nobody knows what it is, deprecate it.

2025-06-17 18:24 UTC, duexw approved these changes
I have removed SiteFrame/rechargingStations as decided at the previous meetings. I have also added references from RechargingStep to the RechargingEquipment and RechargingProfile used. The VDV example is adapted. With these changes, the model is basically compatible with VDV 452.  I therefore approve of this pull request in its current state.

2025-06-18 15:19 UTC, ue71603 approved these changes

2025-06-18 15:19 UTC, skinkie commented on xsd/netex_framework/netex_reusableComponents/netex_nm_equipmentEnergy_support.xsd
> +			<xsd:enumeration value="tpg"/>
I'll remove it in NeTEx 3.0. It will be #922

2025-06-18 15:20 UTC, merged

2025-07-03 10:10 UTC, Aurige commented
PArt 1 & 2 documents were updated