Type of PublicCode
NeTEx-CEN/NeTEx pull request #800
Opened 2024-11-18 15:28 UTC by trurlurl

All `PublicCode` elements should be of type `PublicCodeStructure`, `LinePublicCode` probably as well.

2024-11-18 22:24 UTC, ue71603 approved these changes

2024-11-19 01:12 UTC, skinkie commented
For fixes target master.

2024-11-19 01:13 UTC, skinkie requested changes
Redo on master.

2024-11-19 10:11 UTC, skinkie commented
@ue71603 needs cherry pick. I'll do it shortly.

2024-11-19 10:21 UTC, skinkie approved these changes

2024-11-19 10:22 UTC, merged